@extends("layouts.app")
@section("title","Rekrutmen")@section("page-title","Kelola Rekrutmen")
@section("sidebar")@include("layouts.partials.sidebar-admin")@endsection
@section("content")
<div class="flex justify-between items-center mb-6"><p class="text-slate-600">{{ $ormawa->nama }}</p><a href="{{ route('admin.recruitment.create') }}" class="inline-flex items-center gap-2 px-4 py-2.5 bg-gradient-to-r from-blue-600 to-indigo-600 text-white text-sm font-semibold rounded-xl shadow-lg shadow-blue-500/25"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>Buat Rekrutmen</a></div>
<div class="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden"><div class="overflow-x-auto"><table class="w-full"><thead><tr class="bg-slate-50"><th class="px-6 py-3 text-left text-xs font-semibold text-slate-500 uppercase">Judul</th><th class="px-6 py-3 text-center text-xs font-semibold text-slate-500 uppercase">Pelamar</th><th class="px-6 py-3 text-left text-xs font-semibold text-slate-500 uppercase">Periode</th><th class="px-6 py-3 text-center text-xs font-semibold text-slate-500 uppercase">Status</th><th class="px-6 py-3 text-center text-xs font-semibold text-slate-500 uppercase">Aksi</th></tr></thead>
<tbody class="divide-y divide-slate-100">@forelse($recruitments as $r)<tr class="hover:bg-slate-50"><td class="px-6 py-4"><a href="{{ route('admin.recruitment.show', $r) }}" class="font-medium text-blue-600 hover:text-blue-500">{{ $r->judul }}</a></td><td class="px-6 py-4 text-center text-sm">{{ $r->applications_count }}</td><td class="px-6 py-4 text-sm text-slate-600">{{ $r->tanggal_buka->format('d/m/Y') }} - {{ $r->tanggal_tutup->format('d/m/Y') }}</td><td class="px-6 py-4 text-center"><span class="px-2.5 py-0.5 rounded-full text-xs font-medium {{ $r->status === 'dibuka' ? 'bg-green-50 text-green-700' : ($r->status === 'ditutup' ? 'bg-red-50 text-red-700' : 'bg-slate-100 text-slate-600') }}">{{ ucfirst($r->status) }}</span></td>
<td class="px-6 py-4 text-center"><div class="flex items-center justify-center gap-1"><a href="{{ route('admin.recruitment.show', $r) }}" class="p-2 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg" title="Detail"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/></svg></a><a href="{{ route('admin.recruitment.edit', $r) }}" class="p-2 text-slate-400 hover:text-amber-600 hover:bg-amber-50 rounded-lg" title="Edit"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"/></svg></a></div></td></tr>@empty<tr><td colspan="6" class="px-6 py-8 text-center text-slate-400">Belum ada rekrutmen.</td></tr>@endforelse</tbody></table></div>
@if($recruitments->hasPages())<div class="px-6 py-4 border-t border-slate-200">{{ $recruitments->links() }}</div>@endif</div>
@endsection