@extends("layouts.app")
@section("title","Tambah Admin")@section("page-title","Tambah Admin")
@section("sidebar")@include("layouts.partials.sidebar-superadmin")@endsection
@section("content")
<div class="max-w-2xl"><div class="bg-white rounded-2xl border border-slate-200 shadow-sm p-6">
<form method="POST" action="{{ route('superadmin.admin.store') }}" class="space-y-5">@csrf
<div><label class="block text-sm font-medium text-slate-700 mb-1">Nama *</label><input type="text" name="name" value="{{ old('name') }}" required class="w-full px-4 py-2.5 border border-slate-300 rounded-xl focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500">@error('name')<p class="mt-1 text-xs text-red-500">{{ $message }}</p>@enderror</div>
<div><label class="block text-sm font-medium text-slate-700 mb-1">Email *</label><input type="email" name="email" value="{{ old('email') }}" required class="w-full px-4 py-2.5 border border-slate-300 rounded-xl focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500">@error('email')<p class="mt-1 text-xs text-red-500">{{ $message }}</p>@enderror</div>
<div><label class="block text-sm font-medium text-slate-700 mb-1">Password *</label><input type="password" name="password" required class="w-full px-4 py-2.5 border border-slate-300 rounded-xl focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500">@error('password')<p class="mt-1 text-xs text-red-500">{{ $message }}</p>@enderror</div>
<div><label class="block text-sm font-medium text-slate-700 mb-2">Assign ke Ormawa *</label><div class="space-y-2 max-h-48 overflow-y-auto border border-slate-200 rounded-xl p-3">@foreach($ormawas as $o)<label class="flex items-center gap-2 cursor-pointer p-2 hover:bg-slate-50 rounded-lg"><input type="checkbox" name="ormawa_ids[]" value="{{ $o->id }}" {{ in_array($o->id, old('ormawa_ids', [])) ? 'checked' : '' }} class="w-4 h-4 rounded border-slate-300 text-blue-600"><span class="text-sm text-slate-700">{{ $o->nama }}</span></label>@endforeach</div>@error('ormawa_ids')<p class="mt-1 text-xs text-red-500">{{ $message }}</p>@enderror</div>
<div class="flex gap-3 pt-2"><button type="submit" class="px-6 py-2.5 bg-gradient-to-r from-blue-600 to-indigo-600 text-white font-semibold rounded-xl shadow-lg shadow-blue-500/25">Simpan</button><a href="{{ route('superadmin.admin.index') }}" class="px-6 py-2.5 bg-slate-100 text-slate-700 font-medium rounded-xl hover:bg-slate-200">Batal</a></div>
</form></div></div>
@endsection