@extends("layouts.app")
@section("title","Kelola Admin")@section("page-title","Kelola Admin")
@section("sidebar")@include("layouts.partials.sidebar-superadmin")@endsection
@section("content")
<div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-6"><p class="text-slate-600">Daftar akun administrator.</p><a href="{{ route('superadmin.admin.create') }}" class="inline-flex items-center gap-2 px-4 py-2.5 bg-gradient-to-r from-blue-600 to-indigo-600 text-white text-sm font-semibold rounded-xl shadow-lg shadow-blue-500/25"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>Tambah Admin</a></div>
<div class="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden"><div class="overflow-x-auto"><table class="w-full"><thead><tr class="bg-slate-50"><th class="px-6 py-3 text-left text-xs font-semibold text-slate-500 uppercase">Nama</th><th class="px-6 py-3 text-left text-xs font-semibold text-slate-500 uppercase">Email</th><th class="px-6 py-3 text-left text-xs font-semibold text-slate-500 uppercase">Ormawa</th><th class="px-6 py-3 text-center text-xs font-semibold text-slate-500 uppercase">Status</th><th class="px-6 py-3 text-center text-xs font-semibold text-slate-500 uppercase">Aksi</th></tr></thead>
<tbody class="divide-y divide-slate-100">@forelse($admins as $admin)<tr class="hover:bg-slate-50"><td class="px-6 py-4 font-medium text-slate-800">{{ $admin->name }}</td><td class="px-6 py-4 text-sm text-slate-600">{{ $admin->email }}</td><td class="px-6 py-4"><div class="flex flex-wrap gap-1">@foreach($admin->ormawas as $o)<span class="px-2 py-0.5 rounded-full text-xs font-medium bg-indigo-50 text-indigo-700">{{ $o->nama }}</span>@endforeach</div></td><td class="px-6 py-4 text-center"><span class="px-2.5 py-0.5 rounded-full text-xs font-medium {{ $admin->is_active ? 'bg-green-50 text-green-700' : 'bg-red-50 text-red-700' }}">{{ $admin->is_active ? 'Aktif' : 'Nonaktif' }}</span></td>
<td class="px-6 py-4 text-center"><div class="flex items-center justify-center gap-2"><a href="{{ route('superadmin.admin.edit', $admin) }}" class="p-2 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"/></svg></a><form method="POST" action="{{ route('superadmin.admin.toggle', $admin) }}">@csrf @method('PATCH')<button class="p-2 text-slate-400 hover:text-amber-600 hover:bg-amber-50 rounded-lg" title="Toggle"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636"/></svg></button></form></div></td></tr>@empty<tr><td colspan="5" class="px-6 py-8 text-center text-slate-400">Belum ada admin.</td></tr>@endforelse</tbody></table></div>
@if($admins->hasPages())<div class="px-6 py-4 border-t border-slate-200">{{ $admins->links() }}</div>@endif</div>
@endsection