@extends("layouts.app")
@section("title","Dashboard Admin")@section("page-title","Dashboard")
@section("sidebar")@include("layouts.partials.sidebar-admin")@endsection
@section("content")
<div class="mb-6"><div class="bg-gradient-to-r from-blue-600 to-indigo-700 rounded-2xl p-4 sm:p-6 text-white"><h3 class="text-lg sm:text-xl font-bold">{{ $ormawa->nama }}</h3><p class="text-blue-100 mt-1 text-sm sm:text-base">{{ $ormawa->kategori }} — Panel Administrator</p></div></div>
<div class="grid grid-cols-1 sm:grid-cols-3 gap-6 mb-8">
<div class="bg-white rounded-2xl p-4 sm:p-6 border border-slate-200 shadow-sm"><p class="text-2xl sm:text-3xl font-bold text-slate-800">{{ $stats['total_rekrutmen'] }}</p><p class="text-sm text-slate-500 mt-1">Total Rekrutmen</p></div>
<div class="bg-white rounded-2xl p-4 sm:p-6 border border-slate-200 shadow-sm"><p class="text-2xl sm:text-3xl font-bold text-slate-800">{{ $stats['rekrutmen_aktif'] }}</p><p class="text-sm text-slate-500 mt-1">Rekrutmen Aktif</p></div>
<div class="bg-white rounded-2xl p-4 sm:p-6 border border-slate-200 shadow-sm"><p class="text-2xl sm:text-3xl font-bold text-slate-800">{{ $stats['total_pelamar'] }}</p><p class="text-sm text-slate-500 mt-1">Total Pelamar</p></div>
</div>
<div class="bg-white rounded-2xl border border-slate-200 shadow-sm"><div class="px-4 sm:px-6 py-4 border-b border-slate-200 flex flex-col sm:flex-row sm:justify-between items-start sm:items-center gap-2"><h3 class="text-base sm:text-lg font-semibold text-slate-800">Rekrutmen Terbaru</h3><a href="{{ route('admin.recruitment.create') }}" class="text-sm text-blue-600 hover:text-blue-500 font-medium">+ Buat Rekrutmen</a></div>
<div class="divide-y divide-slate-100">@forelse($recentRecruitments as $r)<a href="{{ route('admin.recruitment.show', $r) }}" class="block px-4 sm:px-6 py-4 hover:bg-slate-50"><div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2"><div><p class="font-medium text-slate-800 text-sm sm:text-base">{{ $r->judul }}</p><p class="text-xs sm:text-sm text-slate-500">{{ $r->tanggal_buka->format('d M Y') }} — {{ $r->tanggal_tutup->format('d M Y') }}</p></div><span class="px-2.5 py-0.5 rounded-full text-[10px] sm:text-xs font-medium {{ $r->status === 'dibuka' ? 'bg-green-50 text-green-700' : ($r->status === 'ditutup' ? 'bg-red-50 text-red-700' : 'bg-slate-100 text-slate-600') }}">{{ ucfirst($r->status) }}</span></div></a>@empty<div class="px-6 py-8 text-center text-slate-400">Belum ada rekrutmen.</div>@endforelse</div></div>
@endsection